### ISSUE TITLE
Validate user input domain and auth code

### ISSUE THREAD

**Issue by Moomootank** [CSE210-Team-5/CSE210-Team5-Feed-Amalgamator#26]
Feature to ensure that user inputs are valid

**Comment by Moomootank** [comment]
Added functions in the interface layer.
Function to check if domain layer is not valid (returns False if so)
And sanity check upon creation of user api client to see if the access code provided works.

Food for thought: Should sanity check be done before saving token to database? Will violate separation of concerns on the backend though.

**Comment by vancheeswaran** [comment]
Duplicate Issue #32
