### ISSUE TITLE
Refactoring of back end code

### ISSUE THREAD

**Issue by Moomootank** [CSE210-Team-5/CSE210-Team5-Feed-Amalgamator#27]
**Contributors:** @Moomootank and @srinivasraman18 

**Scope / Problem Definition:**

Will need to refactor back end code to meet coding standards and adhere to clean code principles.

Comments from professor regarding the starter code as a guideline:

Notes from discussion with Professor:

- #### No abstraction, security, happy path (code only thinks about things that right, not robust code)
- #### magic values/strings, sql injection, robustness, Swagger file/OpenAPI format for documentation

**Deliverables:**

Refactored backend code adhering to coding standards.

**Related Issues:** #25 

**Updates:**
feed.py has been refactored, but will need to be touched up later on(especially regarding error handling)

**Comment by bwu2018** [comment]
Closed with #95
