### ISSUE TITLE
Add user name and password validation in the front end

### ISSUE THREAD

**Issue by srinivasraman18** [CSE210-Team-5/CSE210-Team5-Feed-Amalgamator#32]
**Contributors:** @ju-ra-96 

**Scope / Problem Definition:**

Add the following features in the front end:

- Impose constraints for user name
- Impose constraints for password
- Check if passwords match
- enhance login and register ui

All these features should be implemented as either HTML/Javascript. 

**Deliverables:**

Front end that incorporates the above mentioned features.

**Comment by bwu2018** [comment]
Hitting enter does not automatically submit form in Safari according to @vancheeswaran.

**Comment by ju-ra-96** [comment]
I am done

**Comment by vancheeswaran** [comment]
Might need @bwu2018 and @ju-ra-96 to coordinate and make this work better

**Comment by bwu2018** [comment]
Closed by #83
