### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by srinivasraman18** [CSE210-Team-5/CSE210-Team5-Feed-Amalgamator#34]
**Contributors:** @bwu2018 @ju-ra-96 

**Scope / Problem Definition:** 

Improve the look/feel of UI. Adhere to HTML/CSS and UI/UX standards. Use bootstrap if necessary. 

**Deliverables:**

Better looking UI with improvements to the feed page, settings page, login/register page.

**Comment by bwu2018** [comment]
#23

**Comment by bwu2018** [comment]
#52

**Comment by bwu2018** [comment]
Dealt with login/register #32
