### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by srinivasraman18** [CSE210-Team-5/CSE210-Team5-Feed-Amalgamator#35]
**Contributors:** @Moomootank 

**Scope / Problem Definition:** 

Add unit tests for flask. Aim for 60% code coverage to start with.

**Relevant Links:**

- https://flask.palletsprojects.com/en/3.0.x/testing/
- https://docs.python.org/3/library/unittest.html

**Deliverables:**

Code coverage > 60%

**Comment by bwu2018** [comment]
Going to different pages should not return error and instead redirect (i.e. not logged in going to home page redirects to login instead of throwing error or crashing).

**Comment by Moomootank** [comment]
Added some unit tests, not complete yet.

**Comment by Moomootank** [comment]
Adding unit tests to match the new error handling. Some more refactoring and unit tests are likely required. For tests involving uncertain data from the Mastodon API, a visual End to End test may be more appropriate in the short run due to the complexity of making such tests.

**Comment by Moomootank** [comment]
Refactored some code in mastodon_oauth_interface, and added a (rather crucial) unit test for checking if the amalgamation is actually working.

Good news, it does!

**Comment by bwu2018** [comment]
Closed with #87
