### ISSUE TITLE
[Backlog] Login after database deletion

### ISSUE THREAD

**Issue by bwu2018** [CSE210-Team-5/CSE210-Team5-Feed-Amalgamator#44]
If after you log in the server shuts down and the database is deleted, the cookie will remain unless you completely close the browser (not only that tab). This causes problems when restarting the server and recreating the database because the server thinks you are a returning user, but the database is empty and therefore throws an error.

**Comment by bwu2018** [comment]
Fix might be to check if sql query returns error and to logout user if it does.

**Comment by vancheeswaran** [comment]
I had a discussion with @srinivasraman18 and we decided that this is the expected behaviour. However, we are thinking of adding a keep me signed in checkbox, so that if the tab is closed, we can destroy the session. We can discuss more on this and assign it to someone.

**Comment by vancheeswaran** [comment]
Low Priority

**Comment by vancheeswaran** [comment]
Closing this. Explore this maybe in the next iteration of Feed Amalgamator :)
