### ISSUE TITLE
CI/CD Flow Diagram : Final Draft

### ISSUE THREAD

**Issue by vancheeswaran** [CSE210-Team-5/CSE210-Team5-Feed-Amalgamator#76]
**Contributors:** @ShibaniL123 

**Scope / Problem Definition:**

Create final CI/CD Flow Diagram

**Deliverables:**

Final CI/CD Flow Diagram
https://miro.com/app/board/uXjVNTogQXA=/?moveToWidget=3458764573027731821&cot=14

**Comment by bwu2018** [comment]
Completed on miro: https://miro.com/app/board/uXjVNTogQXA=/?moveToWidget=3458764573027731821&cot=14
