### ISSUE TITLE
[SPIKE] UI Design

### ISSUE THREAD

**Issue by vancheeswaran** [CSE210-Team-5/CSE210-Team5-Feed-Amalgamator#8]
Contributors: @ju-ra-96, @samarth9201 and @bwu2018 

Scope: Designing the Front-End design of the application using Figma and create mock-ups. Once done we can start with implementation. In the first step we build the structure, in the second we work on the design and in the final step on the interactions. After finalizing the mock-ups we can work on implementing them.

Relevant Links:
https://www.figma.com/files/project/153858063/Team-project?fuid=1307481244153586370

Deliverables:
Figma Designs

**Comment by bwu2018** [comment]
Closed because have created basic mock-ups.
